services:
    random-epsilon:
        container_name: random-epsilon
        image: random-epsilon:latest
        restart: on-failure:3
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3002:3002
        networks:
            - nginx

networks:
    nginx:
        name: nginx
        external: true
